<<<<<<< HEAD
name: CI/CD Pipeline

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [pipeline-setup]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Check formatting
      run: npm run format

    - name: Run tests
      run: npm run test

    - name: Build frontend
      run: npm run build
=======
# .github/workflows/ci.yml

name: Otto_CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm ci

      - name: Run frontend lint
        working-directory: ./client
        run: npm run lint

      - name: Run frontend tests
        working-directory: ./client
        run: npm run test

      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci

      - name: Run backend lint
        working-directory: ./server
        run: npm run lint

      - name: Run backend tests
        working-directory: ./server
        run: npm test
>>>>>>> ba4132479e5c14d7c9bf08da4ede80a93cd3b345
